import { isCPF, isCNPJ, formatCNPJ, formatCPF } from './modules/cpfcnpj.module'
import { isPhoneNumber, formatPhoneNumber } from './modules/phonenumber.module'
import {
    minDate,
    maxDate,
    formatDate,
    isDate,
    datesInPeriod,
} from './modules/dates.module'
import {
    isEmpty,
    onlyNumbers,
    isNumber,
    isEmail,
    minChar,
    maxChar,
    allValuesAreEmpty,
    formatMoney,
    randNumber,
} from './modules/methods.module'

export {
    isCPF,
    isCNPJ,
    formatCNPJ,
    formatCPF,
    isPhoneNumber,
    formatPhoneNumber,
    minDate,
    maxDate,
    formatDate,
    isDate,
    datesInPeriod,
    isEmpty,
    onlyNumbers,
    isNumber,
    isEmail,
    minChar,
    maxChar,
    allValuesAreEmpty,
    formatMoney,
    randNumber,
}

export default {
    isCPF,
    isCNPJ,
    formatCNPJ,
    formatCPF,
    isPhoneNumber,
    formatPhoneNumber,
    minDate,
    maxDate,
    formatDate,
    isDate,
    datesInPeriod,
    isEmpty,
    onlyNumbers,
    isNumber,
    isEmail,
    minChar,
    maxChar,
    allValuesAreEmpty,
    formatMoney,
    randNumber,
}
